baseURL = 'https://glolichen.github.io/'
locale = 'en-us'
title = 'Jayden Li'
theme = 'hugo-xmin'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "blog"
    name = "Rambling"
    url = "/blog/"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

[markup.goldmark.renderer]
	unsafe = true
